spring:
  application:
    name: spring-laboratory
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  thymeleaf:
    prefix: classpath:/templates/views/
    cache: false # Production environment enabled
  datasource:
    name: THRAEX-DB
    url: jdbc:mysql://localhost:3306/thraex-admin
    username: root
    password: mysql

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid

thraex:
  mvc:
    webjars: classpath:/META-INF/resources/webjars
    resources:
      - paths:
          - /favicon.ico
          - /assets/**
        locations: classpath:/templates/assets/
      - paths: /vue/**
        locations: ${thraex.mvc.webjars}/vue/2.6.11/
      - paths: /AdminLTE/**
        locations: ${thraex.mvc.webjars}/AdminLTE/3.0.5/
      - paths: /element-ui/**
        locations: ${thraex.mvc.webjars}/element-ui/2.13.2/
      - paths: /axios/**
        locations: ${thraex.mvc.webjars}/axios/0.19.2/
      - paths: /qs/**
        locations: ${thraex.mvc.webjars}/qs/6.9.4/
    views:
      dashboard: dashboard
      demo: demo
      user: demo2/user
