spring:
  application:
    name: spring-laboratory
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
  thymeleaf:
    cache: false # Production environment enabled
    prefix: classpath:/templates/views/
