spring:
  application:
    name: spring-laboratory
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
  thymeleaf:
    prefix: classpath:/templates/views/
    cache: false # Production environment enabled

thraex:
  site:
    title: THRAEX | Dashboard
    logo: ${thraex.site.admin-lte}/dist/img/AdminLTELogo.png
    brand: THRAEX
    admin-lte: /webjars/AdminLTE/3.0.5
