spring:
  application:
    name: spring-laboratory
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
  thymeleaf:
    prefix: classpath:/templates/views/
    cache: false # Production environment enabled
  datasource:
    name: THRAEX-DB
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thraex-admin
    username: root
    password: mysql

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
      table-prefix: tbl_

logging:
  level:
    org.thraex.platform.mapper: debug

thraex:
  site:
    title: THRAEX | Admin
    logo: /AdminLTE/dist/img/AdminLTELogo.png
    brand: THRAEX
  mvc:
    webjars: classpath:/META-INF/resources/webjars
    resources:
      - paths:
          - /favicon.ico
          - /assets/**
        locations: classpath:/templates/assets/
      - paths: /vue/**
        locations: ${thraex.mvc.webjars}/vue/2.6.11/
      - paths: /AdminLTE/**
        locations: ${thraex.mvc.webjars}/AdminLTE/3.0.5/
      - paths: /element-ui/**
        locations: ${thraex.mvc.webjars}/element-ui/2.13.2/
      - paths: /axios/**
        locations: ${thraex.mvc.webjars}/axios/0.19.2/
      - paths: /qs/**
        locations: ${thraex.mvc.webjars}/qs/6.9.4/
    views:
      - dashboard
      - menu
      - user
      - role
      - grant
  user:
    init-password: 111111
