spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agriculture?characterEncoding=utf-8

logging:
  level:
    org.thraex.project.mapper: debug

thraex:
  site:
    admin:
      title: 保定市唐县农业农村局信息管理系统
      brand: 农业农村局
      dashboard: /project/dashboard
  mvc:
    views:
      project-list: project/list
      project-edit: project/edit
