thraex:
  mvc:
    views:
      advert: hbis/advert
      case: hbis/case
  site:
    enabled: true
    admin:
      title: HBIS | Admin
      brand: HBIS
      dashboard: /advert
    portal:
      view: hbis/index
