spring:
  application:
    name: spring-laboratory
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
  thymeleaf:
    prefix: classpath:/templates/views/
    cache: false # Production environment enabled
  datasource:
    name: THRAEX-DB
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/THRAEX-ADMIN
    username: root
    password: mysql

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
      table-prefix: tbl_

logging:
  level:
    org.thraex.platform.mapper: debug

thraex:
  site:
    title: THRAEX | Admin
    logo: /AdminLTE/dist/img/AdminLTELogo.png
    brand: THRAEX
  user:
    init-password: 111111
