spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hbis

logging:
  level:
    org.thraex.business.hbis.mapper: debug

thraex:
  mvc:
    views:
      maint-advert: hbis/maint/advert
      maint-case: hbis/maint/case
      maint-company: hbis/maint/company
  site:
    enabled: true
    admin:
      title: HBIS | Admin
      brand: HBIS
      dashboard: /maint-advert
    portal:
      title: ${hbis.title}
      view: forward:/hbis
    permits:
      - /vue/**
      - /AdminLTE/**
      - /element-ui/**
      - /axios/**
      - /qs/**
      - /assets/**
      - /hbis/**

hbis:
  title: 邯钢集团信达科技有限公司
  nav-code: MENU_HBIS_NAV
