spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hbis

thraex:
  mvc:
    views:
      maint-advert: hbis/maint/advert
      maint-case: hbis/maint/case
  site:
    enabled: true
    admin:
      title: HBIS | Admin
      brand: HBIS
      dashboard: /maint-advert
    portal:
      view: hbis/index
