spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hbis?serverTimezone=GMT
    password: root

logging:
  level:
    org.hbis.business.hbis.mapper: debug

thraex:
  mvc:
    views:
      maint-advert: hbis/maint/advert
      maint-case: hbis/maint/case
      maint-company: hbis/maint/company
      maint-news: hbis/maint/news
      maint-additional-professional: hbis/maint/additional
      maint-additional-cases: hbis/maint/additional
      maint-additional-culture: hbis/maint/additional
  site:
    enabled: true
    admin:
      title: HBIS | Admin
      logo: ${hbis.logo}
      brand: HBIS
      dashboard: /maint/case
    portal:
      title: ${hbis.name}
      logo: ${hbis.logo}
      view: forward:/hbis
    permits:
      - /vue/**
      - /AdminLTE/**
      - /element-ui/**
      - /axios/**
      - /qs/**
      - /assets/**
      - /hbis/**
  favicon: classpath:/templates/assets/images/hbis/
  file:
    directory: /thraex-files

hbis:
  nav-code: MENU_HBIS_NAV
  name: 邯钢集团信达科技有限公司
  logo: /assets/images/hbis/logo.png
  cover-path: /assets/images/hbis/company/cover.png
  introduction: 邯郸市邯钢集团信达科技有限公司（简称信达科技），系河钢集团邯钢公司全资子公司，注册资本500万元，1997年成立。历经邯钢20年基础自动化的高速发展和信息化改造的曲折进程，通过引进消化吸收、联合、自主等途径，实施了涵盖钢铁冶金行业全工艺流程的自动化、信息化系统。凭借服务邯钢的经验和技术积累，信达科技面向社会持续发展，已经成长为能够提供自动化、信息化、通讯、监控等系统解决方案的高新技术企业。
